version: '3.7'

volumes:
  emqx_data:
  influxdb_data:
  grafana_data:

services:
    emqx:
      image: emqx/emqx:5.1.1
      container_name: weather-emqx
      restart: always
      ports:
        - "1883:1883"
        - "18083:18083"
      environment:
        - EMQX_HOST=127.0.0.1
        - EMQX_CRL_CACHE__REFRESH_INTERVAL=1m
        - EMQX_CRL_CACHE__HTTP_TIMEOUT=10s
        - EMQX_MQTT__MAX_PACKET_SIZE=1MB
        - EMQX_RETAINER__BACKEND__STORAGE_TYPE=ram
      volumes:
        - emqx_data:/opt/emqx/data/
      networks:
        - weather-station-network

    influxdb:
      image: influxdb:1.8.10
      container_name: weather-influxdb
      hostname: weather-influxdb
      ports:
        - "8086:8086"
      environment:
        - INFLUX_DB=weather
        - INFLUXDB_ADMIN_USER=admin
        - INFLUXDB_ADMIN_PASSWORD=admin
      restart: always
      networks:
        - weather-station-network

    grafana:
      image: grafana/grafana:7.4.2
      container_name: eb-grafana
      hostname: eb-grafana
      ports:
        - 3000:3000
      volumes:
        - grafana_data:/var/lib/grafana
      networks:
        - weather-station-network
      restart: always

networks:
  weather-station-network:
    driver: "bridge"