version: '3.7'

volumes:
  emqx_data:

services:
    emqx:
      image: emqx/emqx:5.1.1
      container_name: weather-emqx
      restart: always
      ports:
        - "1883:1883"
        - "18083:18083"
      environment:
        - EMQX_HOST=127.0.0.1
        - EMQX_CRL_CACHE__REFRESH_INTERVAL=1m
        - EMQX_CRL_CACHE__HTTP_TIMEOUT=10s
        - EMQX_MQTT__MAX_PACKET_SIZE=1MB
        - EMQX_RETAINER__BACKEND__STORAGE_TYPE=ram
      volumes:
        - emqx_data:/opt/emqx/data/
      networks:
        - weather-station-network

networks:
  weather-station-network:
    driver: "bridge"